# Generated by Django 5.1.3 on 2024-11-25 17:31

import MovieFinder.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_age_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=15, unique=True, validators=[MovieFinder.accounts.validators.UsernameValidator()]),
        ),
    ]
