# Generated by Django 5.1.3 on 2024-12-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_actor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
    ]
