# Generated by Django 5.1.3 on 2024-12-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_remove_actor_movies'),
        ('movies', '0022_remove_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='all_movies',
            field=models.ManyToManyField(related_name='movie_actors', to='movies.movie'),
        ),
    ]
