# Generated by Django 5.1.3 on 2024-11-27 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_comment_created_at_comment_text_comment_to_movie_and_more'),
        ('movies', '0010_remove_movie_awards_movie_main_actors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'to_movie')},
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rate',
        ),
    ]
