# Generated by Django 5.1.3 on 2024-11-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('released_date', models.DateField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('horror', 'Horror'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('biography', 'Biography'), ('anime', 'Anime'), ('musical', 'Musical'), ('mistery', 'Mistery'), ('crime', 'Crime'), ('adventure', 'Adventure'), ('documentary', 'Documentary'), ('sci-fi', 'Sci-Fi'), ('sport', 'Sport'), ('western', 'Western')])),
                ('awards', models.TextField()),
                ('resume', models.TextField(max_length=300)),
            ],
        ),
    ]
