# Generated by Django 5.1.3 on 2024-11-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_id',
            field=models.URLField(blank=True, null=True),
        ),
    ]
