# Generated by Django 5.1.3 on 2024-11-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_trailer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('comedy', 'Comedy'), ('horror', 'Horror'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('biography', 'Biography'), ('anime', 'Anime'), ('musical', 'Musical'), ('mistery', 'Mistery'), ('crime', 'Crime'), ('adventure', 'Adventure'), ('documentary', 'Documentary'), ('sci-fi', 'Sci-Fi'), ('sport', 'Sport'), ('western', 'Western')]),
        ),
    ]
