# Generated by Django 5.1.3 on 2024-11-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Thriller', 'Thriller'), ('Biography', 'Biography'), ('Anime', 'Anime'), ('Musical', 'Musical'), ('Mistery', 'Mistery'), ('Crime', 'Crime'), ('Adventure', 'Adventure'), ('Documentary', 'Documentary'), ('Sci-fi', 'Sci-Fi'), ('Sport', 'Sport'), ('Western', 'Western')]),
        ),
    ]
