# Generated by Django 5.1.3 on 2024-11-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movie_awards_movie_main_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='main_actors',
        ),
    ]
