# Generated by Django 5.1.3 on 2024-11-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_movie_main_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='resume',
            field=models.CharField(max_length=300),
        ),
    ]
