# Generated by Django 5.1.3 on 2024-11-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_rename_nationality_actor_country'),
        ('movies', '0016_alter_movie_main_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='main_actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='main_actors',
            field=models.ManyToManyField(related_name='all_movies', to='actors.actor'),
        ),
    ]
