# Generated by Django 5.1.3 on 2024-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_remove_movie_main_actors_movie_main_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
