# Generated by Django 5.1.3 on 2024-11-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_alter_movie_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='main_actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='main_actors',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
