# Generated by Django 5.1.3 on 2024-12-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_remove_actor_movies'),
        ('movies', '0020_remove_movie_main_actors_movie_main_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='main_actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movie_actors', to='actors.actor'),
        ),
    ]
