# Generated by Django 5.1.3 on 2024-12-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_remove_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
